#!/bin/sh
#
# An example hook script to verify what is about to be committed.
# Called by "git commit" with no arguments.  The hook should
# exit with non-zero status after issuing an appropriate message if
# it wants to stop the commit.
#
# To enable this hook, rename this file to "pre-commit".

STAGED_GO_FILES=$(git diff --cached --name-only | grep ".go$")

if [[ "$STAGED_GO_FILES" = "" ]]; then
  echo "No go files changed"
  exit 0
fi

PASS=true

for FILE in $STAGED_GO_FILES
do
    goimports -w $FILE

    gocritic check $FILE

    golint "-set_exit_status" $FILE
    if [[ $? == 1 ]]; then
        PASS=false
    fi

    go vet $FILE
    if [[ $? != 0 ]]; then
        PASS=false
    fi
done

if ! $PASS; then
    printf "COMMIT FAILED\n"
    exit 1
else
    printf "COMMIT SUCCEEDED\n"
fi

exit 0
