services:
  ohmytp:
    build:
      context: ..
      dockerfile: deploy/Dockerfile
    ports:
      - "8080:8080"
    env_file:
      - .env
    depends_on:
      - redis
      - postgres
    command: ["r"]
  redis:
    image: "redis"
    volumes:
      - redis_data:/var/lib/redis/data
    ports:
      - "6379:6379"
    env_file:
      - .env
    command: [ "sh", "-c", "redis-server --requirepass $REDIS_API_PASSWORD" ]
    restart: unless-stopped
  postgres:
    image: "postgres:latest"
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment: # MUST list the variables here
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_USER}
    env_file:
      - .env
    restart: unless-stopped
volumes:
  redis_data:
  postgres_data: