info:
  contact: {}
paths:
  /ping:
    get:
      consumes:
      - application/json
      description: Responds with "pong"
      produces:
      - application/json
      responses:
        "200":
          description: pong
          schema:
            type: string
      summary: Ping
      tags:
      - Health
swagger: "2.0"
