// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package repository

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Otp struct {
	ID            string
	RequestID     string
	RouteType     pgtype.Text
	Code          pgtype.Text
	RequestedAt   pgtype.Timestamptz
	ConfirmedAt   pgtype.Timestamptz
	ExpiredAt     pgtype.Timestamptz
	Attempt       pgtype.Int2
	LastAttemptAt pgtype.Timestamptz
	ResendAttempt pgtype.Int2
	ResendAt      pgtype.Timestamptz
	IpAddress     pgtype.Text
	UserAgent     pgtype.Text
	CreatedAt     pgtype.Timestamptz
	UpdatedAt     pgtype.Timestamptz
	DeletedAt     pgtype.Timestamptz
}
